// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-m-QyZDeipJLVkFDnX2ohK5_m5LMIkk',
    appId: '1:600333531615:web:66e7ce42a4709d40896c6a',
    messagingSenderId: '600333531615',
    projectId: 'lingopanda-assignment',
    authDomain: 'lingopanda-assignment.firebaseapp.com',
    storageBucket: 'lingopanda-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8hms7rjELkxs7ul6MuR6PIb1DBGwQ_9Q',
    appId: '1:600333531615:android:43a7a846158b6c66896c6a',
    messagingSenderId: '600333531615',
    projectId: 'lingopanda-assignment',
    storageBucket: 'lingopanda-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARfQHMdYznnP9W3Ro4tLg_iRj7bykIz_k',
    appId: '1:600333531615:ios:a6ea270ca0ad9ea3896c6a',
    messagingSenderId: '600333531615',
    projectId: 'lingopanda-assignment',
    storageBucket: 'lingopanda-assignment.appspot.com',
    iosBundleId: 'com.example.lingopanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARfQHMdYznnP9W3Ro4tLg_iRj7bykIz_k',
    appId: '1:600333531615:ios:a6ea270ca0ad9ea3896c6a',
    messagingSenderId: '600333531615',
    projectId: 'lingopanda-assignment',
    storageBucket: 'lingopanda-assignment.appspot.com',
    iosBundleId: 'com.example.lingopanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc-m-QyZDeipJLVkFDnX2ohK5_m5LMIkk',
    appId: '1:600333531615:web:5f4f0f79ae21cd1a896c6a',
    messagingSenderId: '600333531615',
    projectId: 'lingopanda-assignment',
    authDomain: 'lingopanda-assignment.firebaseapp.com',
    storageBucket: 'lingopanda-assignment.appspot.com',
  );
}
